/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.sppk.tampilan;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class kasirTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form kasirTransaksi
     */
    public kasirTransaksi() {
        initComponents();
    }

    public JButton getSelesai() {
        return selesai;
    }

    public JLabel getTotal() {
        return total;
    }
    

    public JButton getKembali() {
        return kembali;
    }
    

    public JTextField getJumlah() {
        return jumlah;
    }

    public JComboBox<String> getProduk() {
        return produk;
    }

    public JTable getTabelTransaksi() {
        return tabelTransaksi;
    }

    public JButton getTambah() {
        return tambah;
    }

    public JComboBox<String> getTipe() {
        return tipe;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        tipe = new javax.swing.JComboBox<>();
        produk = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Produk = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 1260, 530));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sppk/res/tambah.png"))); // NOI18N
        tambah.setBorder(null);
        tambah.setBorderPainted(false);
        tambah.setContentAreaFilled(false);
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "Makanan Ringan", "Makanan Berat", "Makanan Penunjang" }));
        tipe.setBorder(null);
        getContentPane().add(tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 180, 30));

        produk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 180, 30));
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 30));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sppk/res/batal.png"))); // NOI18N
        kembali.setBorder(null);
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, -1, -1));

        selesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sppk/res/simpan.png"))); // NOI18N
        selesai.setBorder(null);
        selesai.setBorderPainted(false);
        selesai.setContentAreaFilled(false);
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, -1, -1));

        total.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("00000");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 290, 30));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jumlah");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 30));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Makanan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 30));

        Produk.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Produk.setForeground(new java.awt.Color(255, 255, 255));
        Produk.setText("Produk");
        getContentPane().add(Produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 30));

        total1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        total1.setForeground(new java.awt.Color(255, 255, 255));
        total1.setText("Total : Rp");
        getContentPane().add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 80, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sppk/res/bg1.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasirTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasirTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasirTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasirTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasirTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Produk;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> produk;
    private javax.swing.JButton selesai;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tambah;
    private javax.swing.JComboBox<String> tipe;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    // End of variables declaration//GEN-END:variables
}
